{{ $project := .Values.projects.infrastructure }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $project.name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  project: {{ $project.name }}
  revisionHistoryLimit: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  source:
    path: {{ tpl $project.path . }}
    repoURL: {{ $project.repoUrl }}
    targetRevision: {{ $project.branch }}
    helm:
      values: |
        global:
          projectName: {{.Values.projects.infrastructure.name}}
          source:
            appsBasePath: {{.Values.projects.infrastructure.path}}
            repoURL: {{.Values.projects.infrastructure.repoUrl}}
            targetRevision: {{.Values.projects.infrastructure.branch}}
        {{- tpl .Values.applicationValues . | nindent 12}}
      valueFiles:
        - values.yaml