# Custom Values which are handed over to the application
applicationValues: |-
${APPLICATION_VALUES}
projects:
  infrastructure:
    name: ${PROJECT_NAME}
    repoUrl: ${PROJECT_SOURCE_REPO_URL}
    path: ${PROJECT_SOURCE_PATH}
    branch: ${PROJECT_BRANCH}
  gitToken:
    name: ${GIT_ACCESS_TOKEN_USERNAME}
    password: ${GIT_ACCESS_TOKEN}
argo-cd:
  controller:
    logFormat: json
    env:
      - name: TZ
        value: Europe/Berlin
  repoServer:
    logFormat: json
    env:
      - name: TZ
        value: Europe/Berlin
  dex:
    env:
      - name: TZ
        value: Europe/Berlin
  server:
    env:
      - name: TZ
        value: Europe/Berlin
    logFormat: json
    extraArgs:
      - "--insecure"
      - "--rootpath=/argocd"
      - "--basehref=/argocd"